// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEzU1n7betwTm2fEnstxChPJhG-OSWhsw',
    appId: '1:245961985733:web:d061cb50439ad9ccf16aac',
    messagingSenderId: '245961985733',
    projectId: 'slc-sdp',
    authDomain: 'slc-sdp.firebaseapp.com',
    storageBucket: 'slc-sdp.firebasestorage.app',
    measurementId: 'G-DDNWNVTJXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-Yb9K_aLLfWVr8FZ2e2ot4qYyJtndp0',
    appId: '1:245961985733:android:176be92c2a865978f16aac',
    messagingSenderId: '245961985733',
    projectId: 'slc-sdp',
    storageBucket: 'slc-sdp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWw0-GykotV2rkLnLhpLrauKp2AucAVMA',
    appId: '1:245961985733:ios:68185bf53f912b21f16aac',
    messagingSenderId: '245961985733',
    projectId: 'slc-sdp',
    storageBucket: 'slc-sdp.firebasestorage.app',
    iosBundleId: 'com.example.slc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWw0-GykotV2rkLnLhpLrauKp2AucAVMA',
    appId: '1:245961985733:ios:68185bf53f912b21f16aac',
    messagingSenderId: '245961985733',
    projectId: 'slc-sdp',
    storageBucket: 'slc-sdp.firebasestorage.app',
    iosBundleId: 'com.example.slc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEzU1n7betwTm2fEnstxChPJhG-OSWhsw',
    appId: '1:245961985733:web:e0d0ca3d49b5480df16aac',
    messagingSenderId: '245961985733',
    projectId: 'slc-sdp',
    authDomain: 'slc-sdp.firebaseapp.com',
    storageBucket: 'slc-sdp.firebasestorage.app',
    measurementId: 'G-Z0Z0W6FHJQ',
  );

}